-- Product translations import
-- Generated from: /Users/Vleras' Macbook Air/Downloads/product_translations_import.csv
-- Rows: 66
-- Idempotent: safe to re-run. Existing (product_id, locale) rows will be updated.

BEGIN;

INSERT INTO public.product_translations
  (product_id, locale, name, description_1, description_2, description_3)
VALUES
  (1, 'en', 'Oval Cryotherapy Bathtub', 'Boost your muscle recovery with the AVACR7 Cryoimmersion Tub, designed to give you the full benefits of cryoimmersion in a practical, effective and safe way. Whether at home, in the gym or in training centres, this tub is the ideal choice for anyone who takes their body seriously.', 'With its compact oval design and quick assembly, it adapts easily to any space. The structure is made from resistant and durable materials, guaranteeing thermal comfort and durability even with frequent use.', 'Exposure to cold water helps reduce inflammation and muscle pain, improves circulation and sleep quality, as well as strengthening the immune system and increasing physical endurance.
Invigorate your body, recover more efficiently and feel the difference with the AVA Cryoimmersion Bath - your cryoimmersion ally.'),
  (1, 'mk', 'Овална када за криотерапија', 'Зголемете го опоравувањето на мускулите со AVACR7 када за криоимерзија, дизајнирана да ви ги понуди целосните придобивки од криоимерзијата на практичен, ефикасен и безбеден начин. Без разлика дали е дома, во теретана или во тренинг центри, оваа када е идеален избор за секој кој сериозно се грижи за своето тело.', 'Со својот компактен овален дизајн и брзо склопување, лесно се приспособува на секој простор. Структурата е направена од отпорни и издржливи материјали, гарантирајќи топлински комфор и издржливост дури и при честа употреба.', 'Изложеноста на студена вода помага да се намали воспалението и мускулната болка, го подобрува циркулацијата и квалитетот на сонот, а истовремено го зајакнува имунолошкиот систем и ја зголемува физичката издржливост.
Освежете го своето тело, опоравувајте се поефикасно и почувствувајте разлика со AVA када за криоимерзија - вашиот сојузник во криоимерзијата.'),
  (2, 'en', 'Roller Massage Stick', 'Ideal for muscle relief anywhere', 'The massage stick is the perfect solution for those who want to relieve muscle pain quickly. It helps reduce tension and promotes relaxation in a practical and efficient way.', 'With its ergonomic design and textured roller, it provides a deep and comfortable massage, ideal for use on areas such as the legs, back, shoulders and arms. Helps reduce muscle fatigue, improves circulation and speeds up post-workout recovery.'),
  (2, 'mk', 'Стап за масажа со ролер', 'Идеален за мускулно олеснување каде и да сте', 'Стапот за масажа е совршено решение за оние кои сакаат брзо да ослободат мускулна болка. Помага да се намали тензијата и промовира релаксација на практичен и ефикасен начин.', 'Со својот ергономски дизајн и текстуриран ролер, обезбедува длабока и комфорна масажа, идеална за употреба на делови како нозете, грбот, рамениците и рацете. Помага да се намали мускулниот замор, го подобрува циркулацијата и го забрзува опоравувањето по тренинг.'),
  (3, 'en', 'Inflatable Leg and Foot Cushion', 'The inflatable leg and foot cushion is designed to help relieve pain quickly, as well as help reduce swelling and improve blood circulation.', 'Compact, lightweight and easy to carry, it''s perfect for use at home, in the office or when travelling. It is also ideal as a complementary accessory to LedBoots, AVABoots and Cryo Sport, further enhancing their therapeutic effects.', 'Made from resistant PVC, this cushion is easy to clean. The ergonomic design adapts to your body, ensuring practical rest and comfort.
Take care of your recovery in comfort - relieve aches and pains and feel light on your legs with the AVA inflatable cushion.'),
  (3, 'mk', 'Надуваема перница за нозе и стопала', 'Надуваемата перница за нозе и стопала е дизајнирана да помогне брзо да се олесни болката, како и да помогне да се намали отокот и да се подобри циркулацијата на крвта.', 'Компактна, лесна и лесна за носење, идеална е за употреба дома, во канцеларија или при патување. Исто така е идеална како комплементарен додаток на LedBoots, AVABoots и Cryo Sport, дополнително зголемувајќи ги нивните терапевтски ефекти.', 'Направена од отпорен PVC, оваа перница е лесна за чистење. Ергономскиот дизајн се приспособува на вашето тело, обезбедувајќи практичен одмор и комфор.
Погрижете се за вашето опоравување во комфор - олеснете болки и болежливост и почувствувајте леснотија во нозете со AVA надуваемата перница.'),
  (4, 'en', 'Inflatable Bucket', 'Advanced, fast and effective muscle recovery.', 'Speed up your recovery with our round tub. Perfect for cryotherapy at home, in the gym or in training centres. Developed for athletes and recovery enthusiasts, this tub combines therapeutic efficiency, compact design, simple assembly and made from strong, durable materials.', 'Cryotherapy sessions help reduce swelling and relieve muscle pain by improving blood circulation. They also improve sleep quality and strengthen the immune system.'),
  (4, 'mk', 'Надуваема када', 'Напредно, брзо и ефикасно опоравување на мускулите.', 'Забрзајте го вашето опоравување со нашата кружна када. Совршена за криотерапија дома, во теретана или во тренинг центри. Развиена за спортисти и љубители на опоравувањето, оваа када комбинира терапевтска ефикасност, компактен дизајн, едноставно склопување и е направена од јаки, издржливи материјали.', 'Сесиите за криотерапија помагаат да се намали отокот и да се олесни мускулната болка со подобрување на крвната циркулација. Тие исто така подобруваат квалитетот на сонот и го зајакнуваат имунолошкиот систем.'),
  (5, 'en', 'Charging Base', 'Ensure that your Pro Physio Pro and Pro Physio Pro Max massage guns are always ready. The AVA Charging Base is ideal for those who value practicality, efficiency and design.', 'With fast and safe induction charging, it keeps your equipment charged and ready whenever you need it. The compact design fits easily into any environment, whether at home, in the gym or at the office.', 'Equipped with LED status indicators and USB-C connection, it allows for a full recharge in around 3 hours, without any hassle.'),
  (5, 'mk', 'Базна станица за полнење', 'Осигурајте се дека вашите масажни пиштоли Pro Physio Pro и Pro Physio Pro Max се секогаш подготвени. AVA базната станица за полнење е идеална за оние кои ценат практичност, ефикасност и дизајн.', 'Со брзо и безбедно индукциско полнење, ја чува вашата опрема наполнета и подготвена кога ви е потребна. Компактниот дизајн лесно се вклопува во секоја околина, без разлика дали е дома, во теретана или во канцеларија.', 'Опремена со LED индикатори за статус и USB-C конекција, овозможува целосно полнење за околу 3 часа, без никакви проблеми.'),
  (7, 'en', 'AVABoots', 'Fully wireless compression boots, lightweight and easily controlled through the "Avaboots" app.', 'Adjustable compression from 70 to 185 mmHg, with four compression chambers and three distinct programs. Ideal for reducing the impact of intense training, improving muscle recovery, promoting lymphatic drainage and blood circulation, and maximizing performance.', NULL),
  (7, 'mk', 'AVABoots', 'Целосно безжични компресивни чизми, лесни и лесно контролирани преку апликацијата „Avaboots“.', 'Прилагодлива компресија од 70 до 185 mmHg, со четири компресивни комори и три различни програми. Идеални за намалување на влијанието на интензивните тренинзи, подобрување на мускулното опоравување, промовирање на лимфна дренажа и крвна циркулација, и максимизирање на перформансите.', NULL),
  (8, 'en', 'Ice Ball', 'The AVA Ice Ball is your ally for fast relief of muscle pain, reduction of swelling and effective post-workout recovery. With a stainless steel ball that stays cold for up to 6 hours, it provides the benefits of cryotherapy without the need for compresses or ice packs.', 'It combines the action of ice with massage in a single device, allowing you to apply localised pressure with a cooling effect, ideal for physiotherapy, muscle relaxation and reducing inflammation after physical exertion.', 'Compact, lightweight and easy to transport, you can use it at home, in the gym or during professional appointments.'),
  (8, 'mk', 'Ледена топка', 'AVA ледената топка е вашиот сојузник за брзо олеснување на мускулната болка, намалување на отокот и ефикасно опоравување по тренинг. Со топче од нерѓосувачки челик кое остане ладно до 6 часа, обезбедува придобивките од криотерапија без потреба од компреси или ледени пакувања.', 'Ја комбинира дејството на мразот со масажа во еден уред, дозволувајќи ви да примените локализиран притисок со ефект на ладење, идеален за физиотерапија, мускулна релаксација и намалување на воспалението по физички напор.', 'Компактна, лесна и лесна за пренесување, можете да ја користите дома, во теретана или при професионални термини.'),
  (9, 'en', 'Bosu', 'It''s an ideal tool for improving your balance, strength and flexibility in one versatile piece of equipment. Whether in the gym, at home or in pilates studios, the balance and strength ball (BOSU) adapts easily to different types of training, from physiotherapy to strength training, to functional and rehabilitation exercises.', 'With its non-slip design and elasticated resistance bands with rubber grips, it allows you to work various muscle groups with stability and safety. It''s perfect for developing the core, improving posture, motor coordination and body control.', 'It can hold up to 200kg, is made from resistant materials and comes with a pump so you''re always ready to train.
Challenge your body, improve your stability and take your workouts to the next level with the BOSU AVA.'),
  (9, 'mk', 'Босу', 'Тоа е идеална алатка за подобрување на вашата рамнотежа, сила и флексибилност во едно универзално парче опрема. Без разлика дали е во теретана, дома или во пилатес студија, топката за рамнотежа и сила (BOSU) лесно се приспособува на различни видови тренинг, од физиотерапија до тренинг на сила, до функционални и рехабилитациски вежби.', 'Со својот дизајн против лизгање и еластични ленти за отпор со гумени рачки, дозволува да работите на различни мускулни групи со стабилност и безбедност. Совршена е за развивање на јадрото, подобрување на положбата, моторната координација и контролата на телото.', 'Може да поднесе до 200кг, направена е од отпорни материјали и доаѓа со пумпа за да сте секогаш подготвени за тренинг.
Предизвикајте го вашето тело, подобрете ја вашата стабилност и подигнете ги вашите тренинзи на следното ниво со BOSU AVA.'),
  (10, 'en', 'Massage chair', 'The AVA Massage Chair is the ideal choice if you''re looking for practicality, comfort and mobility for your massage sessions. Lightweight, foldable and easy to assemble, it goes wherever you need it - whether in corporate environments, events, clinics or at home.', 'With an ergonomic design and high-quality synthetic material padding, it adapts well to different body morphologies and works with different massage techniques, guaranteeing maximum comfort.', 'This chair is designed for health professionals and athletes who value efficiency and portability.
Raise the quality of your care with mobility and comfort - with the AVA Massage Chair, you''re always ready for care.'),
  (10, 'mk', 'Стол за масажа', 'AVA столот за масажа е идеален избор ако барате практичност, комфор и мобилност за вашите сесии на масажа. Лесен, склопувачки и лесен за монтирање, оди каде и да ви е потребен - без разлика дали во корпоративни средини, настани, клиники или дома.', 'Со ергономски дизајн и подлога од висококвалитетен синтетички материјал, добро се приспособува на различни телесни морфологии и работи со различни техники на масажа, гарантирајќи максимален комфор.', 'Овој стол е дизајниран за здравствени професионалци и спортисти кои ценат ефикасност и преносливост.
Подигнете го квалитетот на вашата нега со мобилност и комфор - со AVA столот за масажа, секогаш сте подготвени за нега.'),
  (11, 'en', 'Recovery Chair', 'The Recovery Chair is ideal for those looking for comfort and muscle recovery. It''s perfect for your home, clinics, offices, spas and physiotherapy centres.', 'With a strong steel frame, this chair supports up to 160kg and has adjustable leg supports. It has a cushion that can be adjusted, safety locks and a compartment for storing objects. This guarantees maximum functionality in every session.', 'The modern design and anti-fall function make the product ideal for intensive use in recovery and well-being.
Raise the standard of your recovery sessions with the safety, comfort and performance of the AVA Recovery Chair.'),
  (11, 'mk', 'Стол за опоравување', 'Столот за опоравување е идеален за оние кои бараат комфор и мускулно опоравување. Совршен е за вашиот дом, клиники, канцеларии, спа центри и физиотерапевтски центри.', 'Со јака рамка од челик, овој стол поддржува до 160кг и има подесиви потпори за нозете. Има перница која може да се подесува, безбедносни брави и одделение за складирање на предмети. Ова гарантира максимална функционалност во секоја сесија.', 'Модерниот дизајн и функцијата против пад го прават производот идеален за интензивна употреба во опоравување и благосостојба.
Подигнете го стандардот на вашите сесии за опоравување со безбедноста, комфорот и перформансите на AVA столот за опоравување.'),
  (12, 'en', 'Chiller', 'The AVA Chiller is the smart solution for your cryotherapy tub, helping you to recover your muscles. With precise temperature control, no more hassle with ice during your cryotherapy sessions.', 'With a powerful 1 HP (735 W) motor, this cooling system guarantees constant and effective cooling. It''s perfect for AVA cryotherapy baths, whether in professional environments or at home. Its compact design and energy efficiency make it easy to install and use, offering safe, fast and comfortable sessions.', 'Power up your cryotherapy tub with the AVA Chiller - total thermal control for faster, more practical and effective recovery.'),
  (12, 'mk', 'Чилер', 'AVA чилерот е паметно решение за вашата када за криотерапија, помагајќи ви да опоравите вашите мускули. Со прецизна контрола на температурата, нема повеќе проблеми со мраз за време на вашите сесии на криотерапија.', 'Со мотор со моќ од 1 HP (735 W), овој систем за ладење гарантира постојано и ефикасно ладење. Совршен е за AVA када за криотерапија, без разлика дали е во професионални средини или дома. Неговиот компактен дизајн и енергетска ефикасност го прават лесен за инсталирање и употреба, нудејќи безбедни, брзи и комфорни сесии.', 'Зголемете ја моќта на вашата када за криотерапија со AVA чилерот - целосна термална контрола за побрзо, попрактично и поефикасно опоравување.'),
  (13, 'en', 'AquaBag Cylinder', 'Turn instability into strength with the AquaBag Cylinder AVA. It''s perfect for anyone who wants to challenge their body with a functional, dynamic and effective workout. With internal water oscillations, you''ll activate stabilising muscles, improve your balance, strength and endurance in a real and progressive way.', 'The AquaBag cylinder has load markings from 5 to 25kg. This allows you to adjust the weight precisely to your goal. It''s perfect for core training, mobility, rehabilitation, HIIT and athletic preparation.', 'Made from tough, durable PVC, it has five reinforced handles for maximum stability, comfort and versatility in any type of exercise.'),
  (13, 'mk', 'AquaBag Цилиндрична', 'Претворете ја нестабилноста во сила со AquaBag Цилиндрична AVA. Совршена е за секој кој сака да го предизвика своето тело со функционален, динамичен и ефикасен тренинг. Со внатрешните осцилации на водата, ќе ги активирате стабилизирачките мускули, ќе ја подобрите вашата рамнотежа, сила и издржливост на реален и прогресивен начин.', 'AquaBag цилиндрот има ознаки за оптоварување од 5 до 25кг. Ова ви дозволува прецизно да го приспособите тежината на вашата цел. Совршена е за тренинг на јадрото, мобилност, рехабилитација, HIIT и атлетска подготовка.', 'Направена од јак, издржлив PVC, има пет зајакнати рачки за максимална стабилност, комфор и универзалност во секој вид вежба.'),
  (14, 'en', 'Cryo Sport', 'The only device that combines cryotherapy, active compression, portability, and real-time thermal imaging.', 'Ideal for athletes, sports teams, and clinics looking to reduce recovery time, increase performance, and achieve more consistent results.', NULL),
  (14, 'mk', 'Cryo Sport', 'Единствениот уред кој комбинира криотерапија, активна компресија, преносливост и термално снимање во реално време.', 'Идеален за спортисти, спортски тимови и клиники кои сакаат да го намалат времето на опоравување, да зголемат перформанси и да постигнат постојани резултати.', NULL),
  (15, 'en', 'Myofascial release kit', 'The AVA Myofascial Release Kit is designed to help relieve muscle pain, improve flexibility and speed up physical recovery effectively and safely. It''s a complete solution for anyone who takes their body seriously - whether it''s intense training or daily clinical work.', 'This kit includes 316 surgical steel tools, ideal for applying muscle release, mobilisation and rehabilitation techniques. The smooth surface and balanced weight of each piece guarantee precision in touch and comfort in use.', 'Perfect for athletes, physiotherapists, personal trainers and other health professionals. It comes with an anti-shock case, protecting the equipment and making it easy to transport.
Free your body from discomfort. Improve your performance and recover with precision. With the AVA Myofascial Release Kit, you have the power in your hands.'),
  (15, 'mk', 'Комплет за миофасцијално ослободување', 'AVA комплетот за миофасцијално ослободување е дизајниран да помогне во олеснување на мускулната болка, подобрување на флексибилноста и забрзување на физичкото опоравување ефикасно и безбедно. Тоа е целосно решение за секој кој сериозно се грижи за своето тело - без разлика дали е интензивен тренинг или секојдневна клиничка работа.', 'Овој комплет вклучува 316 алатки од хируршки челик, идеални за примена на техники за мускулно ослободување, мобилизација и рехабилитација. Мазната површина и балансираната тежина на секое парче гарантираат прецизност во допирот и комфор во употребата.', 'Совршен за спортисти, физиотерапевти, лични тренери и други здравствени професионалци. Доаѓа со куфер против удари, штитејќи ја опремата и правејќи ја лесна за пренесување.
Ослободете го вашето тело од непријатност. Подобрете ги перформансите и опоравувајте се со прецизност. Со AVA комплетот за миофасцијално ослободување, моќта е во вашите раце.'),
  (16, 'en', 'LedBoots', 'Advanced muscle recovery through photobiomodulation with high-performance LED technology.', 'LedBoots* combine LED therapy (red light and infrared light) with ergonomic compression to accelerate tissue regeneration, improve blood circulation, reduce pain, and promote anti-inflammatory action. A portable, comfortable, and effective solution for smart recovery.', '*includes 1 LED boot, adjustable to the leg (one size fits all)
Get 20% off when you purchase your second Ledboot.'),
  (16, 'mk', 'LedBoots', 'Напредно мускулно опоравување преку фотобиомодулација со високо-перформансна LED технологија.', 'LedBoots* комбинираат LED терапија (црвена и инфрацрвена светлина) со ергономска компресија за забрзување на регенерацијата на ткивата, подобрување на крвната циркулација, намалување на болката и промовирање на антиинфламаторно дејство. Практично, комфорно и ефикасно решение за паметно опоравување.', '*вклучува 1 LED чизма, приспособлива на нозето (една големина за сите)
Добијте 20% попуст кога ќе го купите вашиот втор Ledboot.'),
  (17, 'en', 'Cryo Sport Travel Bag', 'The Cryo Sport Travel Bag is perfect if you want to take your cryotherapy equipment with you safely and in style. With a strong, modern design, this bag is made for athletes, physiotherapists, professionals and sports lovers who travel a lot.', 'Constructed from high-quality materials, the protection of your Cryo Sport is guaranteed. It resists shocks, scratches and damage during transport. Take your performance everywhere - transport your Cryo Sport with complete safety and confidence.', NULL),
  (17, 'mk', 'Патна торба за Cryo Sport', 'Патната торба за Cryo Sport е совршена ако сакате да ја носите вашата опрема за криотерапија со себе безбедно и со стил. Со јак, модерен дизајн, оваа торба е направена за спортисти, физиотерапевти, професионалци и љубители на спортот кои често патуваат.', 'Направена од висококвалитетни материјали, заштитата на вашиот Cryo Sport е гарантирана. Издржува удари, гребнатини и штета за време на транспорт. Носете ги вашите перформанси секаде - транспортирајте го вашиот Cryo Sport со целосна безбедност и доверба.', NULL),
  (18, 'en', 'Foot massager', 'Do your feet feel tired or do you spend a lot of time standing?', 'Designed to reduce fatigue and relieve built-up tension, whether from intense workouts or demanding days, the AVA foot massager provides immediate relief and deep relaxation.', 'A practical and effective solution to promote comfort, recovery, and daily well-being.'),
  (18, 'mk', 'Масажер за стопала', 'Дали вашите стопала се чувствуваат уморни или трошите многу време стоејќи?', 'Дизајниран да намали замор и да олесни насобрана тензија, без разлика дали од интензивни тренинзи или напорни дена, AVA масажерот за стопала обезбедува непосредно олеснување и длабока релаксација.', 'Практично и ефикасно решение за промовирање на комфор, опоравување и секојдневна благосостојба.'),
  (19, 'en', 'Pro Physio', 'Pro Physio was developed to deliver professional-grade percussion massage, combining power, control, and quiet operation in an ergonomic and durable device.', 'Designed for those who demand maximum effectiveness in muscle recovery, it provides deep and targeted action, ideal for preparation, recovery, and physical maintenance.', 'Clinical performance in the palm of your hand.'),
  (19, 'mk', 'Pro Physio', 'Pro Physio беше развиен да обезбеди перкусивна масажа од професионален степен, комбинирајќи моќ, контрола и тивка работа во ергономски и издржлив уред.', 'Дизајниран за оние кои бараат максимална ефикасност во мускулното опоравување, обезбедува длабоко и таргетирано дејство, идеално за подготовка, опоравување и физичко одржување.', 'Клиничка изведба во дланката на вашата рака.'),
  (21, 'en', 'Vibrating Massage Roller', 'The AVA Vibrating Massage Roller is the ideal equipment to improve your pre-workout, muscle recovery and physical performance. With five speed levels and adjustable frequency, you can personalise each massage session. It helps relieve aches and pains, relax muscles and activate circulation.', 'Designed with three different textures, it stimulates the muscles at various depths and angles, optimising myofascial work. Made from high-density EVA foam, it guarantees durability, comfort and stability even during intense workouts.', 'Lightweight and practical, it''s ideal for use at home, in the gym or after training. It helps you recover faster, reduces tension and prevents injuries.'),
  (21, 'mk', 'Вибрирачки ролер за масажа', 'AVA вибрирачкиот ролер за масажа е идеална опрема за подобрување на вашата подготовка пред тренинг, мускулното опоравување и физичките перформанси. Со пет нивоа на брзина и прилагодлива фреквенција, можете да персонализирате секоја сесија на масажа. Помага да се олесни болка и болежливост, да се релаксираат мускулите и да се активира циркулацијата.', 'Дизајниран со три различни текстури, стимулира мускулите на различни длабочини и агли, оптимизирајќи миофасцијалната работа. Направен од висококвалитетна EVA пена, гарантира издржливост, комфор и стабилност дури и за време на интензивни тренинзи.', 'Лесен и практичен, идеален е за употреба дома, во теретана или по тренинг. Помага да се опоравите побрзо, намалува тензија и превенира повреди.'),
  (22, 'en', 'Warm Pro', 'Warm Pro is a thermal belt that combines uniform heating with adjustable vibration to promote muscle relaxation, relieve lower back pain, and prepare the body for exercise.', 'Compact and portable, it is a practical and effective solution to relieve lower back pain and tension, reduce stiffness, and accelerate muscle recovery in everyday life.', NULL),
  (22, 'mk', 'Warm Pro', 'Warm Pro е термален појас кој комбинира еднакво загревање со прилагодлива вибрација за промовирање на мускулна релаксација, олеснување на болка во долниот дел на грбот и подготовка на телото за вежбање.', 'Компактен и преносен, тоа е практично и ефикасно решение за олеснување на болка и тензија во долниот дел на грбот, намалување на вкочанетост и забрзување на мускулното опоравување во секојдневниот живот.', NULL),
  (23, 'en', 'Actin One', 'Portable EMS + TENS Electro Stimulator for Recovery and Performance.', 'Actin One combines TENS (for pain relief) and EMS (for muscle strengthening) technologies in a compact, professional device designed to relieve pain, accelerate recovery, and enhance physical performance.', 'Clinical evidence, total control, and precision in a portable device that adapts to different stages of training and rehabilitation.'),
  (23, 'mk', 'Actin One', 'Преносен EMS + TENS електростимулатор за опоравување и перформанси.', 'Actin One комбинира TENS (за олеснување на болка) и EMS (за зајакнување на мускулите) технологии во компактен, професионален уред дизајниран да олесни болка, забрза опоравување и подобри физички перформанси.', 'Клинички докази, целосна контрола и прецизност во преносен уред кој се приспособува на различни фази на тренинг и рехабилитација.'),
  (25, 'en', 'AVAPress', 'AVAPress compression socks were developed to improve blood circulation, reduce muscle fatigue, and accelerate recovery, whether during training, competition, travel, or long periods of standing.', 'Lightweight, technical, and comfortable, they keep up with your pace without compromising performance.', NULL),
  (25, 'mk', 'AVAPress', 'AVAPress компресивните чорапи беа развиени за подобрување на крвната циркулација, намалување на мускулниот замор и забрзување на опоравувањето, без разлика дали за време на тренинг, натпревар, патување или долги периоди на стоење.', 'Лесни, технички и комфорни, држат темпо со вас без да ги нарушат перформансите.', NULL),
  (26, 'en', 'Bioimpedance scale', 'Professional Body Assessment with High Accuracy and Technology.', 'The AVABio380 is a bioimpedance scale that uses several frequencies. It is designed for anyone who cares about their body, such as health and sports professionals. This scale offers a complete, fast and reliable body analysis.', 'The BIA (bioelectrical impedance) technology takes readings at three frequencies: 5, 50 and 250 kHz. This provides more than 20 indicators of body composition. It includes lean mass, body fat and total water. It also measures water inside and outside cells, visceral fat and bone mass.
Its modern, ergonomic and portable design comes with an exclusive anti-shock case that guarantees safe transport.
Connectivity is easy and efficient via an app. Data is synchronised via Bluetooth with the free AVABio380 app.'),
  (26, 'mk', 'Биоимпедансна вага', 'Професионална телесна проценка со висока прецизност и технологија.', 'AVABio380 е биоимпедансна вага која користи неколку фреквенции. Дизајнирана е за секој кој се грижи за своето тело, како здравствени и спортски професионалци. Оваа вага нуди целосна, брза и сигурна анализа на телото.', 'BIA (биоелектрична импеданса) технологијата зема мерења на три фреквенции: 5, 50 и 250 kHz. Ова обезбедува повеќе од 20 индикатори за составот на телото. Вклучува мускулна маса, телесна маст и вкупна вода. Исто така мери вода внатре и надвор од клетките, висцерална маст и коскена маса.
Нејзиниот модерен, ергономски и преносен дизајн доаѓа со ексклузивен куфер против удари кој гарантира безбеден транспорт.
Поврзувањето е лесно и ефикасно преку апликација. Податоците се синхронизираат преку Bluetooth со бесплатната апликација AVABio380.'),
  (27, 'en', 'Mini elasticated bands', 'AVA Mini Bands are perfect for boosting your physical strength, improving flexibility, and taking care of your body anywhere. With two resistance levels (medium and strong), they easily adapt to your goals, offering a complete, functional, and practical workout.', 'Ideal for preventing muscle pain, enhancing physical conditioning, and targeting specific muscle groups, they are essential tools whether you train at home, in the gym, or while traveling.', 'Made from durable, high-quality latex, they ensure effective training for strength building, muscle activation, rehabilitation, and mobility.
Enhance your workouts, train smart, and stay active wherever you are with AVA Mini Bands – simple, effective, and always with you.'),
  (27, 'mk', 'Мини еластични ленти', 'AVA Мини лентите се совршени за зголемување на вашата физичка сила, подобрување на флексибилноста и грижа за вашето тело секаде. Со два нивоа на отпор (среден и силен), лесно се приспособуваат на вашите цели, нудејќи целосен, функционален и практичен тренинг.', 'Идеални за превенција на мускулна болка, подобрување на физичката подготвеност и таргетирање на специфични мускулни групи, се есенцијални алатки без разлика дали тренирате дома, во теретана или додека патувате.', 'Направени од издржлив, висококвалитетен латекс, обезбедуваат ефикасен тренинг за градење сила, мускулна активација, рехабилитација и мобилност.
Подигнете ги вашите тренинзи, тренирајте паметно и останете активни каде и да сте со AVA Мини лентите - едноставни, ефикасни и секогаш со вас.'),
  (28, 'en', 'Super elastic bands', 'AVA''s Super Elastic Bands are great for improving your physical performance. Good for strength training, stretching and muscle rehabilitation. Lightweight, compact and extremely resistant, they adapt to any training routine and all levels - from beginners to advanced athletes.', 'With three levels of resistance (light, medium and strong), you can easily adjust the intensity of your workouts to increase flexibility, improve joint mobility and boost fitness.', 'Ideal for use at home, in the gym or outdoors. An indispensable tool for anyone who wants to maximise results efficiently and safely.
Increase intensity, improve technique and achieve new goals - all with the AVA Super Band by your side.'),
  (28, 'mk', 'Супер еластични ленти', 'AVA-те Супер еластични ленти се одлични за подобрување на вашите физички перформанси. Добри за тренинг на сила, стрејчинг и мускулна рехабилитација. Лесни, компактни и екстремно отпорни, се приспособуваат на секоја тренинг рутина и сите нивоа - од почетници до напредни спортисти.', 'Со три нивоа на отпор (лесен, среден и силен), можете лесно да ја прилагодите интензивноста на вашите тренинзи за да ја зголемите флексибилноста, подобрите мобилноста на зглобовите и подигнете ја кондицијата.', 'Идеални за употреба дома, во теретана или на отворено. Незаменлива алатка за секој кој сака да максимизира резултати ефикасно и безбедно.
Зголемете интензивност, подобрете техника и постигнете нови цели - сите со AVA Супер лентата покрај вас.'),
  (29, 'en', 'AquaBag Ball', 'Strength, Balance and Control in Every Move.', 'Challenge your body with the AquaBag AVA Ball, the perfect tool for anyone who wants to take functional training to a new level. With the dynamic movement of the water inside, you''ll feel a constant instability that activates deep muscles and improves strength, endurance, coordination and balance at the same time.', 'Made of resistant PVC and equipped with two comfortable handles, it guarantees safety and firmness during all exercises. Lightweight and versatile, it adapts to various types of training - at home, in the gym or even outdoors.
The AquaBag Ball can be filled up to 7kg, allowing you to adjust the load according to your level and goals.
Exercise consistently, activate your whole body and feel the positive impact on your performance.'),
  (29, 'mk', 'AquaBag Топка', 'Сила, рамнотежа и контрола во секој потег.', 'Предизвикајте го вашето тело со AquaBag AVA Топка, совршената алатка за секој кој сака да го подигне функционалниот тренинг на ново ниво. Со динамичното движење на водата внатре, ќе почувствувате постојана нестабилност која активира длабоки мускули и подобрува сила, издржливост, координација и рамнотежа во исто време.', 'Направена од отпорен PVC и опремена со две комфорни рачки, гарантира безбедност и цврстина за време на сите вежби. Лесна и универзална, се приспособува на различни видови тренинг - дома, во теретана или дури и на отворено.
AquaBag Топката може да се наполни до 7кг, дозволувајќи ви да го приспособите оптоварувањето според вашето ниво и цели.
Вежбајте постојано, активирајте го целото тело и почувствувајте позитивно влијание на вашите перформанси.'),
  (30, 'en', 'Zero Gravity Recovery Chair', 'The Zero Gravity Recovery Chair is designed to offer you deep relaxation and more effective muscle recovery by elevating your legs for total relaxation. It distributes body weight evenly and reduces pressure on the spine.', 'Perfect for athletes, health professionals or anyone looking to improve blood circulation, relieve back pain and speed up physical recovery. With its sturdy metal frame, comfortable padding and adjustable backrest, it easily adapts to your needs.', 'What''s more, it''s light and easy to carry. This makes it a practical solution for use at home, during physiotherapy sessions or after training.
Give your body the rest it deserves - with the AVA CR7 Recovery Chair, you can relax effectively, comfortably and in style.'),
  (30, 'mk', 'Стол за опоравување со нула гравитација', 'Столот за опоравување со нула гравитација е дизајниран да ви понуди длабока релаксација и поефикасно мускулно опоравување со подигање на нозете за целосна релаксација. Го дистрибуира телесната тежина равномерно и го намалува притисокот на кичмата.', 'Совршен за спортисти, здравствени професионалци или секој кој сака да ја подобри крвната циркулација, олесни болка во грбот и забрза физичко опоравување. Со својата цврста метална рамка, комфорна подлога и подесив наслон, лесно се приспособува на вашите потреби.', 'Штом повеќе, е лесен и лесен за носење. Ова го прави практично решение за употреба дома, за време на сесии на физиотерапија или по тренинг.
Дајте му на вашето тело одморот кој го заслужува - со AVA CR7 столот за опоравување, можете да се релаксирате ефикасно, комфорно и со стил.'),
  (31, 'en', 'Deep Light', 'Advanced LED photobiomodulation. It combines red and infrared light to accelerate recovery, reduce inflammation, relieve pain, and improve the regeneration of cells and tissues.', 'Deep Light is a non-invasive, portable, and easy-to-use device.', NULL),
  (31, 'mk', 'Deep Light', 'Напредна LED фотобиомодулација. Комбинира црвена и инфрацрвена светлина за забрзување на опоравувањето, намалување на воспалението, олеснување на болка и подобрување на регенерацијата на клетките и ткивата.', 'Deep Light е неинвазивен, преносен и лесен за употреба уред.', NULL),
  (33, 'en', 'MiniGun', 'The MiniGun is a massage gun designed to provide effective muscle relief, reduce built-up tension, and speed up recovery wherever you are.', 'Compact and lightweight, it easily fits into your routine. Professional power in a portable format.', NULL),
  (33, 'mk', 'MiniGun', 'MiniGun е пиштол за масажа дизајниран да обезбеди ефикасно мускулно олеснување, намалување на насобраната тензија и забрзување на опоравувањето каде и да сте.', 'Компактен и лесен, лесно се вклопува во вашата рутина. Професионална моќ во преносен формат.', NULL),
  (35, 'en', 'CR7 Backpack', 'The AVA Backpack was designed to offer durability, practicality, and comfort for carrying your equipment. With a dedicated laptop compartment, it''s perfect for balancing your professional and athletic life.', 'Designed for your daily routine, it features an ergonomic height, padded back support, and adjustable straps—ensuring total comfort even during long commutes or extended use.', 'Whether in professional settings, training sessions, clinical appointments, or travel, this backpack goes with you, offering versatility and strength while keeping your gear protected and organized.
Stay efficient, protect your devices, and take your recovery tools with you— with the AVA Backpack, everything you need is right at hand, wherever and whenever you need it.'),
  (35, 'mk', 'CR7 Ранец', 'AVA ранецот беше дизајниран да понуди издржливост, практичност и комфор за носење на вашата опрема. Со посветено одделение за лаптоп, совршен е за балансирање на вашиот професионален и спортски живот.', 'Дизајниран за вашата секојдневна рутина, содржи ергономска висина, подложена поддршка за грбот и подесиви ремени - обезбедувајќи целосен комфор дури и за време на долги патувања или продолжена употреба.', 'Без разлика дали е во професионални средини, тренинг сесии, клинички термини или патувања, овој ранец оди со вас, нудејќи универзалност и јачина додека ја чува вашата опрема заштитена и организирана.
Останете ефикасни, заштитете ги вашите уреди и носете ги вашите алатки за опоравување со себе - со AVA ранецот, сè што ви е потребно е при рака, каде и кога ви е потребно.'),
  (36, 'en', 'Heating tip for MiniGun', 'Massage with heat for deep muscle relief.', 'Enhance your massage experience with the Heating Tip for your MiniGun. Perfect for anyone looking for quick relief from muscle pain with heat therapy.', 'With temperatures ranging from 42°C to 50°C, this tip helps relax muscles, reduces stiffness, improves blood circulation and increases flexibility. It''s the perfect solution to complete your muscle recovery and wellness routine.
Enjoy a professional massage wherever and whenever you want, with the benefits of therapeutic heat. Boost your recovery with advanced technology.'),
  (36, 'mk', 'Загрејна глава за MiniGun', 'Масажа со топлина за длабоко мускулно олеснување.', 'Подигнете го вашето масажно искуство со Загрејната глава за вашиот MiniGun. Совршена за секој кој бара брзо олеснување од мускулна болка со терапија со топлина.', 'Со температури од 42°C до 50°C, оваа глава помага да се релаксираат мускулите, намалува вкочанетост, подобрува крвна циркулација и зголемува флексибилност. Тоа е совршено решение да го комплетирате вашето мускулно опоравување и рутина за благосостојба.
Насладете се на професионална масажа каде и кога сакате, со придобивките од терапевтска топлина. Подигнете го вашето опоравување со напредна технологија.'),
  (37, 'en', 'Heating tip for Pro Physio Pro/Max', 'Massage with heat for deep muscle relief.', 'Enhance your massage experience with the Heating Tip for your Pro Physio Pro and Pro Max. It''s perfect for anyone looking for quick relief from muscle pain with heat therapy.', 'With temperatures ranging from 42°C to 50°C, it helps relax muscles, reduces stiffness, improves blood circulation and increases flexibility. It''s the perfect solution to complement your muscle recovery and wellness routine.
Enjoy a professional massage wherever and whenever you want, with the benefits of therapeutic heat. Boost your recovery with advanced technology.'),
  (37, 'mk', 'Загрејна глава за Pro Physio Pro/Max', 'Масажа со топлина за длабоко мускулно олеснување.', 'Подигнете го вашето масажно искуство со Загрејната глава за вашиот Pro Physio Pro и Pro Max. Совршена е за секој кој бара брзо олеснување од мускулна болка со терапија со топлина.', 'Со температури од 42°C до 50°C, помага да се релаксираат мускулите, намалува вкочанетост, подобрува крвна циркулација и зголемува флексибилност. Тоа е совршено решение да го комплетирате вашето мускулно опоравување и рутина за благосостојба.
Насладете се на професионална масажа каде и кога сакате, со придобивките од терапевтска топлина. Подигнете го вашето опоравување со напредна технологија.'),
  (40, 'en', 'Pro Physio Pro Max', 'The Pro Physio Pro was developed to offer an advanced massage, combining power, precision, and ergonomics in a high-performance device.', 'Ideal for demanding athletes and professionals, it provides a deep action on the muscles, helping to improve mobility, reduce muscle tension, and accelerate recovery after intense workouts.', NULL),
  (40, 'mk', 'Pro Physio Pro Max', 'Pro Physio Pro беше развиен да понуди напредна масажа, комбинирајќи моќ, прецизност и ергономија во уред со високи перформанси.', 'Идеален за барателни спортисти и професионалци, обезбедува длабоко дејство на мускулите, помагајќи да се подобри мобилноста, намали мускулна тензија и забрза опоравувањето по интензивни тренинзи.', NULL)
ON CONFLICT (product_id, locale) DO UPDATE SET
  name          = EXCLUDED.name,
  description_1 = EXCLUDED.description_1,
  description_2 = EXCLUDED.description_2,
  description_3 = EXCLUDED.description_3,
  updated_at    = now();

-- Verify counts per locale
DO $$
DECLARE
  cnt_en int;
  cnt_mk int;
BEGIN
  SELECT COUNT(*) INTO cnt_en FROM public.product_translations WHERE locale = 'en';
  SELECT COUNT(*) INTO cnt_mk FROM public.product_translations WHERE locale = 'mk';
  RAISE NOTICE 'After import: en=%, mk=%', cnt_en, cnt_mk;
END $$;

COMMIT;
